service: python-builds

plugins:
  - serverless-python-requirements
  - serverless-step-functions
  - serverless-pseudo-parameters
custom: ${file(./serverless-custom.yml)}

package:
  exclude:
    - integration/**
    - builder/**
    - docs/**
    - node_modules/**
    - .npm/**
    - .cache/**

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  deploymentBucket:
    name: ${self:custom.deploymentBucket}
  tagsList:
    - Key: rs:project
      Value: ${self:custom.${self:provider.stage}.tags.project}
    - Key: rs:owner
      Value: ${self:custom.${self:provider.stage}.tags.owner}
    - Key: rs:environment
      Value: ${self:custom.${self:provider.stage}.tags.environment}
  tagsMap:
    "rs:owner": ${self:custom.${self:provider.stage}.tags.owner}
    "rs:project": ${self:custom.${self:provider.stage}.tags.project}
    "rs:environment": ${self:custom.${self:provider.stage}.tags.environment}
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - "batch:*"
       Resource: '*'
    -  Effect: Allow
       Action:
         - "s3:*"
       Resource:
        - arn:aws:s3:::${self:custom.${self:provider.stage}.s3Bucket}
        - arn:aws:s3:::${self:custom.${self:provider.stage}.s3Bucket}/*
    -  Effect: Allow
       Action:
         - "sns:Publish"
       Resource:
         Ref: pythonBuildsTopic
  environment:
    S3_BUCKET: ${self:custom.${self:provider.stage}.s3Bucket}
    SNS_TOPIC_ARN:
      Ref: pythonBuildsTopic
    JOB_QUEUE_ARN:
      Ref: pythonBuildsBatchJobQueue
    JOB_DEFINITION_ARN_ubuntu_1804:
      Ref: pythonBuildsBatchJobDefinitionUbuntu1804
    JOB_DEFINITION_ARN_ubuntu_2004:
      Ref: pythonBuildsBatchJobDefinitionUbuntu2004
    JOB_DEFINITION_ARN_ubuntu_2204:
      Ref: pythonBuildsBatchJobDefinitionUbuntu2204
    JOB_DEFINITION_ARN_ubuntu_2404:
      Ref: pythonBuildsBatchJobDefinitionUbuntu2404
    JOB_DEFINITION_ARN_debian_10:
      Ref: pythonBuildsBatchJobDefinitionDebian10
    JOB_DEFINITION_ARN_debian_11:
      Ref: pythonBuildsBatchJobDefinitionDebian11
    JOB_DEFINITION_ARN_debian_12:
      Ref: pythonBuildsBatchJobDefinitionDebian12
    JOB_DEFINITION_ARN_centos_7:
      Ref: pythonBuildsBatchJobDefinitionCentos7
    JOB_DEFINITION_ARN_centos_8:
      Ref: pythonBuildsBatchJobDefinitionCentos8
    JOB_DEFINITION_ARN_rhel_9:
      Ref: pythonBuildsBatchJobDefinitionRhel9
    JOB_DEFINITION_ARN_opensuse_153:
      Ref: pythonBuildsBatchJobDefinitionOpensuse153
    JOB_DEFINITION_ARN_opensuse_154:
      Ref: pythonBuildsBatchJobDefinitionOpensuse154
    SUPPORTED_PLATFORMS: ubuntu-1804,ubuntu-2004,ubuntu-2204,ubuntu-2404centos-7,centos-8,rhel-9,opensuse-153,opensuse-154,debian-10,debian-11,debian-12

functions:
  queueBuilds:
    timeout: 120
    handler: handler.queue_builds
  jobQueueStatus:
    handler: handler.poll_running_jobs
  finished:
    handler: handler.finished


stepFunctions:
  stateMachines: ${file(./serverless-stepf.yml)}

resources:
  Resources: ${file(./serverless-resources.yml)}
