FROM ubuntu:focal

ENV OS_IDENTIFIER ubuntu-2004

RUN set -x \
  && sed -i "s|# deb-src|deb-src|g" /etc/apt/sources.list \
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -y libssl-dev wget python3-pip gnupg ca-certificates

RUN pip3 install awscli

RUN chmod 0777 /opt

COPY build.sh .
ENTRYPOINT ./build.sh
